name: Incue
favicon: null
layout_spectrum: 0.62532
typography_spectrum: 0.4711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18122c'
    - '#ce122c'
    - '#72122c'
    - '#aaaaaa'
    - '#807d7e'
  brandStrength: 0.36093396903015673
  lightness: 0.5596615036483854
  saturation: 0.5230719668325037
  rhythmicContrast: 0.23771136719733477
purpose: []
