name: Incue
favicon: null
layout_spectrum: 0.9451702812220901
typography_spectrum: 0.9333553274627775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.36093396903015673
  lightness: 0.5596615036483854
  saturation: 0.5230719668325037
  rhythmicContrast: 0.23771136719733477
purpose: []
